#!/usr/bin/env python3

import sys
import time
from subprocess import PIPE, run


def load_conf(config_file):

    configuration = {}
    with open(config_file, 'r') as f:

        for line in f.readlines():

            if line[0] == '#':
                continue

            line = line.strip()
            if not ' ' in line:
                continue

            name, value = line.split(' ', 1)
            configuration[name] = value

    return configuration


def take_screenshot():

    # WARNING: Make sure the screenshot is blurry for privacy reasons
    proc = run(['import', '-silent', '-window', 'root', '-thumbnail', '10%', 'png:-'], stdout=PIPE)

    return proc.stdout


if __name__ == '__main__':

    config = load_conf(sys.argv[1])

    # TODO validate configuration values

    config['Port'] = int(config['Port'])
    config['ScreenshotInterval'] = int(config['ScreenshotInterval'])

    next_run_timestamp = time.time()

    while True:

        if next_run_timestamp > time.time():
            time.sleep(.4)
            continue

        next_run_timestamp = time.time() + config['ScreenshotInterval']

        image = take_screenshot()

        # TODO upload blurry screen to server
